### ISSUE TITLE
running .welcome

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#5]
[16:34:08] [Server thread/INFO]: SurestTexas00 joined the game
[16:35:17] [Server thread/INFO]: <SurestTexas00> .welcome Welcome to The Imagine
 Craft NINSS server!!
Error triggering event System.EventHandler`1[NINSS.PlayerChatEventArgs]: Noesis.
Javascript.JavascriptException
Message: Object reference not set to an instance of an object.
Stacktrace:    at Noesis.Javascript.JavascriptContext.Run(String iSourceCode)
   at JavascriptConnector.JavascriptConnector.TriggerEvent(String name, Object[]
 args)
   at NINSS.MinecraftConnector.TriggerEvent[T](EventHandler`1 ev, T args)

**Comment by suresttexas00** [comment]
Works now... might have had a problem in the plugin code.

**Comment by M4GNV5** [comment]
when you get an "JavascriptException" its always an error in the plugin code
it might actually be a good idea to output the error line & column when getting javascript errors instead the C# stacktrace...

**Comment by M4GNV5** [comment]
done: https://github.com/M4GNV5/NINSS/blob/master/plugins/JavascriptConnector/JavascriptPlugin.cs#L31
